(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AgjAkQgPgPAAgVQAAgUAPgPQAPgPAUAAQAVAAAPAPQAPAPAAAUQAAAVgPAPQgPAPgVAAQgUAAgPgPg");
	this.shape.setTransform(11.2,11.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(6.2,6.2,10.100000000000001,10.100000000000001), null);


(lib.SliderButton = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(0.1,2,1).p("AAAiUQAVAAAOAOQAPAPAAAVIAADFQAAAVgPAOQgOAPgVAAQgUAAgPgPQgOgOAAgVIAAjFQAAgVAOgPQAPgOAUAAg");
	this.shape.setTransform(-0.1,-39.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003E74").s().p("AgjCGQgOgOAAgVIAAjFQAAgUAOgQQAQgOATAAQAUAAAPAOQAPAQAAAUIAADFQAAAVgPAOQgPAPgUAAQgTAAgQgPg");
	this.shape_1.setTransform(-0.1,-39.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.1,-55.4,12,31.799999999999997);


(lib.SliderBar = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Regions
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#003E74").ss(0.1,2,1).p("Egn3gAuMBPvAAAIAABdMhPvAAAg");
	this.shape.setTransform(255.225,4.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D4EFFC").s().p("Egn3AAuIAAhcMBPvAAAIAABcg");
	this.shape_1.setTransform(255.225,4.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.SliderBar, new cjs.Rectangle(-1,-1,512.5,11.3), null);


(lib.Symbol22 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_15
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#003E74").ss(3,2,0,3).p("A0FAAMAoLAAA");
	this.shape.setTransform(-38.35,533.75);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(268));

	// Layer_14
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003E74").s().p("AH/RuIAAhIIBHAAIAABIgADvRuIAAhIIBHAAIAABIgAgjRuIAAhIIBGAAIAABIgAkzRuIAAhIIBHAAIAABIgApFRuIAAhIIBHAAIAABIgAH/NiIAAhHIBHAAIAABHgADvNiIAAhHIBHAAIAABHgAgjNiIAAhHIBGAAIAABHgAkzNiIAAhHIBHAAIAABHgApFNiIAAhHIBHAAIAABHgAH/JFIAAhHIBHAAIAABHgADvJFIAAhHIBHAAIAABHgAgjJFIAAhHIBGAAIAABHgAkzJFIAAhHIBHAAIAABHgApFJFIAAhHIBHAAIAABHgAH/EtIAAhIIBHAAIAABIgADvEtIAAhIIBHAAIAABIgAgjEtIAAhIIBGAAIAABIgAkzEtIAAhIIBHAAIAABIgApFEtIAAhIIBHAAIAABIgAH/AhIAAhGIBHAAIAABGgADvAhIAAhGIBHAAIAABGgAgjAhIAAhGIBGAAIAABGgAkzAhIAAhGIBHAAIAABGgApFAhIAAhGIBHAAIAABGgAH/jxIAAhIIBHAAIAABIgADvjxIAAhIIBHAAIAABIgAgjjxIAAhIIBGAAIAABIgAkzjxIAAhIIBHAAIAABIgApFjxIAAhIIBHAAIAABIgAH/n9IAAhHIBHAAIAABHgADvn9IAAhHIBHAAIAABHgAgjn9IAAhHIBGAAIAABHgAkzn9IAAhHIBHAAIAABHgApFn9IAAhHIBHAAIAABHgAH/saIAAhHIBHAAIAABHgADvsaIAAhHIBHAAIAABHgAgjsaIAAhHIBGAAIAABHgAkzsaIAAhHIBHAAIAABHgApFsaIAAhHIBHAAIAABHgAH/wlIAAhIIBHAAIAABIgADvwlIAAhIIBHAAIAABIgAgjwlIAAhIIBGAAIAABIgAkzwlIAAhIIBHAAIAABIgApFwlIAAhIIBHAAIAABIg");
	this.shape_1.setTransform(-30.775,424.225);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).to({_off:true},127).wait(141));

	// Layer_13
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgPA0QALgGAFgNQAFgMAAgVQAAgUgFgMQgFgOgLgFIABgGQAPAHAIAOQAHANAAAXQAAAXgHAOQgIAOgPAHg");
	this.shape_2.setTransform(42.575,543.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#666666").s().p("AgXAdIABgIIAQABIAEAAIAKgBQAEAAABgCQABgCAAgDQAAgEgCgCIgHgCIgQgEQgGgCgEgDQgDgDAAgIQAAgGACgEQADgDAFgBQAEgCAHAAIANABIANABIgBAIIgGgBIgIAAIgKAAIgHABQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBABIgBAEIABAFIADACIAFACIAQAEQAHABADADQADAEAAAHQAAAHgCADQgDAEgFABQgFACgJAAQgLAAgMgCg");
	this.shape_3.setTransform(37.55,544.525);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#666666").s().p("AgEAiQgEgEAAgIIAAgiIgLAAIAAgIIALAAIAAgRIAJAAIAAARIATAAIAAAIIgTAAIAAAhQAAAEACACQACACAEAAIAJAAIABAIIgGABIgHAAQgGAAgEgEg");
	this.shape_4.setTransform(32.225,543.725);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#666666").s().p("AAQAeIAAgoQAAgFgDgDQgBgCgFAAQgEAAgEACIgOAHIAAApIgKAAIAAg5IAJAAIAAAJQAPgLALAAQAHAAAEAEQAFAEAAAIIAAArg");
	this.shape_5.setTransform(26.5,544.45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#666666").s().p("AgEAqIAAg6IAJAAIAAA6gAgBgbQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAgGIABgDIADgBIADAAQABAAABAAQAAABABAAQAAABAAAAQABABAAABIAAAGQAAABgBABQAAAAAAABQgBAAAAABQgBAAgBAAg");
	this.shape_6.setTransform(21.55,543.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#666666").s().p("AgPAcQgGgDgCgHQgDgHgBgLQABgKADgHQACgHAGgDQAGgDAJAAQAKAAAGADQAGADADAHQADAHAAAKQAAALgDAHQgDAHgGADQgGADgKAAQgJAAgGgDgAgJgTQgEACgBAFQgBAEAAAIQAAAJABAEQABAFAEACQAEACAFAAQAGAAAEgCQAEgCABgFQACgEAAgJQAAgIgCgEQgBgFgEgCQgEgCgGAAQgFAAgEACg");
	this.shape_7.setTransform(16.65,544.525);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#666666").s().p("AgIAyIAGgJQABgFAAgFIAAg7IAJAAIAAA7QAAAHgDAGQgDAGgEAEgAABgnQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgGQAAgBAAgBQAAgBAAAAQABgBAAAAQAAAAABAAIAFAAQAAAAABAAQABAAAAABQAAAAABABQAAABAAABIAAAGQAAABAAABQgBAAAAABQAAAAgBAAQgBABAAAAg");
	this.shape_8.setTransform(11.425,544.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#666666").s().p("AgRAeIAAg5IAIAAIABAJQAMgLAMAAIACAAIgBAKIgDAAQgFAAgFACIgLAFIAAAqg");
	this.shape_9.setTransform(5.575,544.45);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#666666").s().p("AgOAcQgFgDgDgHQgDgHAAgLQAAgLADgGQADgHAFgDQAGgDAJAAQANAAAGAFQAGAFAAAJQAAAIgEAEQgDAEgHAAIgaAAQAAAHACAEQACADAEACQAEABAFAAIAUgBIABAGQgDACgHABIgMABQgJAAgHgDgAgHgTQgEABgCAFQgBAEAAAHIAYAAQAFAAAAgJQAAgFgDgDQgDgCgHAAQgGAAgDACg");
	this.shape_10.setTransform(-0.35,544.525);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#666666").s().p("AgRAoQgHgBgCgEQgDgEAAgHQAAgFACgDQADgDAFgDIgDgEIgBgFIABgEQABgDACgBQgEgCgCgEQgBgEAAgFQAAgHACgEQACgEAGgCQAFgCAKAAQAHAAAFABIATAAIgBAGIgJABQADAEAAAGQAAAKgGAFQgGAEgMAAQgIAAgEgBQgBAAAAABQAAABgBAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAAAQAAABABAAQAAABAAAAIAFACIAUADQAJACADAEQADADAAAIQAAAHgCAEQgDAEgGABQgGACgKAAQgKAAgGgCgAgRARQgCADAAADQAAAFACACQABACAEABIALAAIAKAAQAEgBACgCQABgDAAgEIgBgEIgCgDIgHgBIgTgDIgEAFgAgNgfQgEADAAAFQAAAGAEADQADACAJAAQAHAAAEgCQADgDAAgGQAAgFgDgDQgEgCgHAAQgJAAgDACg");
	this.shape_11.setTransform(-6.775,545.675);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#666666").s().p("AAPAeIAAgoQAAgFgBgDQgCgCgFAAQgFAAgEACIgMAHIAAApIgLAAIAAg5IAJAAIAAAJQAOgLAMAAQAHAAAFAEQADAEAAAIIAAArg");
	this.shape_12.setTransform(-13.7,544.45);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#666666").s().p("AgPAcQgGgDgCgHQgDgHAAgLQAAgKADgHQACgHAGgDQAGgDAJAAQAKAAAGADQAGADADAHQADAHAAAKQAAALgDAHQgDAHgGADQgGADgKAAQgJAAgGgDgAgJgTQgDACgCAFQgCAEABAIQgBAJACAEQACAFADACQAEACAFAAQAHAAADgCQAEgCABgFQACgEAAgJQAAgIgCgEQgBgFgEgCQgDgCgHAAQgFAAgEACg");
	this.shape_13.setTransform(-20.6,544.525);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#666666").s().p("AgRAeIAAg5IAIAAIABAJQAMgLAMAAIACAAIgBAKIgDAAQgFAAgFACIgLAFIAAAqg");
	this.shape_14.setTransform(-26.025,544.45);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#666666").s().p("AgEAiQgEgEAAgIIAAgiIgLAAIAAgIIALAAIAAgRIAJAAIAAARIATAAIAAAIIgTAAIAAAhQAAAEACACQACACAEAAIAJAAIABAIIgGABIgHAAQgGAAgEgEg");
	this.shape_15.setTransform(-31.075,543.725);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#666666").s().p("AgXAdIABgIIARABIADAAIAKgBQADAAACgCQACgCgBgDQAAgEgCgCIgHgCIgQgEQgHgCgDgDQgCgDAAgIQAAgGABgEQADgDAFgBQAEgCAHAAIANABIANABIgBAIIgGgBIgIAAIgKAAIgHABQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBABIgBAEIABAFIADACIAFACIAQAEQAHABADADQADAEAAAHQAAAHgCADQgDAEgFABQgFACgJAAQgLAAgMgCg");
	this.shape_16.setTransform(-36.35,544.525);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#666666").s().p("AgIAlQgIgOABgXQgBgWAIgOQAHgOAQgHIABAGQgMAFgEAOQgGAMABAUQgBAVAGAMQAEANAMAGIgBAGQgQgHgHgOg");
	this.shape_17.setTransform(-41.4,543.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#666666").s().p("AgNAcQgGgDgDgHQgDgHAAgLQAAgLADgGQADgHAGgDQAFgDAJAAQANAAAGAFQAGAFAAAJQAAAIgEAEQgDAEgHAAIgaAAQAAAHACAEQACADAEACQAEABAFAAIAUgBIABAGQgDACgHABIgMABQgJAAgGgDgAgHgTQgEABgCAFQgBAEAAAHIAYAAQAFAAAAgJQAAgFgCgDQgEgCgHAAQgGAAgDACg");
	this.shape_18.setTransform(-49.5,544.525);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#666666").s().p("AgIAmQgEgDAAgIIAAhFIAKAAIAABDQAAAEACACQABACAEAAIAGAAIACAIIgGABIgFABQgGAAgEgFg");
	this.shape_19.setTransform(-54.1,543.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#666666").s().p("AgNAqQgHgBgFgDIAAhQIAKAAIAAAWQAAAIgBAFQAKgLALAAQALAAAFAIQAGAHAAAPQgBAKgCAHQgCAHgGADQgFAEgKAAIgOgBgAgGgHIgKAHIABAgQAIACAHAAQAGAAAEgCQADgCABgFQABgFABgIIgCgMQgBgFgDgCQgDgCgGAAQgDAAgEACg");
	this.shape_20.setTransform(-59.55,543.325);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#666666").s().p("AgEAqIAAg6IAJAAIAAA6gAgCgbQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAgGIAAgDIACgBIAFAAQAAAAABAAQAAABABAAQAAABAAAAQABABAAABIAAAGQAAABgBABQAAAAAAABQgBAAAAABQgBAAAAAAg");
	this.shape_21.setTransform(-64.55,543.275);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#666666").s().p("AASAdIgRgaIgBAAIgRAaIgLAAIAUgdIgTgcIALAAIAPAYIACAAIAPgYIALAAIgSAcIAUAdg");
	this.shape_22.setTransform(-69.175,544.525);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#666666").s().p("AgOAcQgFgDgDgHQgDgHAAgLQAAgLADgGQADgHAFgDQAGgDAJAAQANAAAGAFQAGAFAAAJQAAAIgEAEQgDAEgHAAIgaAAQAAAHACAEQACADAEACQAEABAFAAIAUgBIABAGQgDACgHABIgMABQgJAAgHgDgAgHgTQgEABgCAFQgBAEAAAHIAYAAQAFAAAAgJQAAgFgDgDQgDgCgHAAQgGAAgDACg");
	this.shape_23.setTransform(-75.5,544.525);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#666666").s().p("AgHAmQgFgDAAgIIAAhFIAKAAIAABDQAAAEACACQACACADAAIAGAAIACAIIgGABIgFABQgGAAgDgFg");
	this.shape_24.setTransform(-80.1,543.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#666666").s().p("AgKArIAAgxIgLAAIAAgIIALAAIAAgLQAAgJADgEQAFgEAHAAIARABIgBAIIgMAAQgFAAgDACQgBACAAAFIAAAKIASAAIAAAIIgSAAIAAAxg");
	this.shape_25.setTransform(-84.3,543.15);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#666666").s().p("AgXAdIABgIIAQABIAEAAIAKgBQADAAACgCQABgCAAgDQAAgEgCgCIgHgCIgQgEQgGgCgEgDQgDgDAAgIQAAgGACgEQADgDAEgBQAFgCAHAAIANABIANABIgBAIIgGgBIgIAAIgKAAIgHABQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBABIgBAEIABAFIADACIAFACIAQAEQAHABADADQADAEAAAHQAAAHgCADQgDAEgFABQgFACgJAAQgLAAgMgCg");
	this.shape_26.setTransform(-92.5,544.525);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#666666").s().p("AgWAdIAAgIIARABIADAAIAKgBQADAAACgCQACgCgBgDQAAgEgBgCIgIgCIgQgEQgGgCgEgDQgCgDAAgIQAAgGABgEQADgDAFgBQAEgCAHAAIANABIANABIgBAIIgGgBIgIAAIgKAAIgHABQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBABIAAAEIAAAFIADACIAFACIAQAEQAHABAEADQACAEAAAHQABAHgDADQgDAEgFABQgFACgJAAQgLAAgLgCg");
	this.shape_27.setTransform(-98.55,544.525);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#666666").s().p("AgOAcQgFgDgDgHQgDgHAAgLQAAgLADgGQADgHAFgDQAGgDAJAAQANAAAGAFQAGAFAAAJQAAAIgEAEQgDAEgHAAIgaAAQAAAHACAEQACADAEACQAEABAFAAIAUgBIABAGQgDACgHABIgMABQgJAAgHgDgAgHgTQgEABgCAFQgBAEAAAHIAYAAQAFAAAAgJQAAgFgDgDQgDgCgHAAQgGAAgDACg");
	this.shape_28.setTransform(-104.75,544.525);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#666666").s().p("AgUAlQgDgEAAgHIAAhCIAKAAIAABBQAAAEACACQACACAEAAIAdAAIAAAIIgeABQgJAAgFgFg");
	this.shape_29.setTransform(-110.7,543.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("#003E74").ss(3,2,0,3).p("AIkRJMAAAgiRAGYRJMAAAgiRAmaRJMAAAgiRAojRJMAAAgiRAEQRJMAAAgiRAiJRJMAAAgiRAAARJMAAAgiRACHRJMAAAgiRAkSRJMAAAgiR");
	this.shape_30.setTransform(-30.65,424.075);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#666666").s().p("AgOAcQgGgDgCgHQgDgHAAgLQAAgLADgGQACgHAGgDQAGgDAJAAQANAAAGAFQAGAFAAAJQAAAIgDAEQgEAEgHAAIgaAAQABAHACAEQACADADACQAEABAFAAIAVgBIABAGQgEACgGABIgNABQgJAAgHgDgAgIgTQgDABgBAFQgCAEgBAHIAYAAQAHAAAAgJQAAgFgEgDQgDgCgIAAQgFAAgEACg");
	this.shape_31.setTransform(4.55,544.525);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#666666").s().p("AgIAmQgDgDAAgIIAAhFIAKAAIAABDQAAAEABACQABACAFAAIAFAAIABAIIgEABIgGABQgGAAgEgFg");
	this.shape_32.setTransform(-0.05,543.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#666666").s().p("AgMAqQgIgBgGgDIAAhQIALAAIAAAWQAAAIgCAFQALgLALAAQALAAAGAIQAEAHAAAPQAAAKgCAHQgDAHgFADQgGAEgKAAIgMgBgAgFgHIgKAHIAAAgQAIACAHAAQAGAAADgCQAEgCABgFQACgFAAgIIgCgMQAAgFgDgCQgEgCgFAAQgEAAgDACg");
	this.shape_33.setTransform(-5.5,543.325);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#666666").s().p("AgEAqIAAg6IAJAAIAAA6gAgBgbQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAgGIABgDIADgBIADAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAAGQAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAg");
	this.shape_34.setTransform(-10.5,543.275);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#666666").s().p("AgNAcQgHgDgCgHQgDgHAAgLQAAgLADgGQACgHAHgDQAFgDAJAAQANAAAGAFQAGAFAAAJQAAAIgDAEQgEAEgHAAIgaAAQABAHACAEQACADADACQAEABAFAAIAVgBIABAGQgEACgGABIgNABQgJAAgGgDgAgIgTQgDABgBAFQgCAEgBAHIAYAAQAHAAAAgJQAAgFgDgDQgEgCgIAAQgFAAgEACg");
	this.shape_35.setTransform(-21.45,544.525);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#666666").s().p("AgIAmQgDgDAAgIIAAhFIAKAAIAABDQAAAEABACQABACAFAAIAFAAIABAIIgEABIgGABQgGAAgEgFg");
	this.shape_36.setTransform(-26.05,543.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#666666").s().p("AgLArIAAgxIgKAAIAAgIIAKAAIAAgLQAAgJAFgEQADgEAIAAIARABIgBAIIgMAAQgGAAgCACQgBACgBAFIAAAKIASAAIAAAIIgSAAIAAAxg");
	this.shape_37.setTransform(-30.25,543.15);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#666666").s().p("AgPAcQgGgDgCgHQgEgHAAgLQAAgKAEgHQACgHAGgDQAGgDAJAAQAKAAAGADQAGADADAHQACAHAAAKQAAALgCAHQgDAHgGADQgGADgKAAQgJAAgGgDgAgJgTQgDACgCAFQgBAEAAAIQAAAJABAEQACAFADACQADACAGAAQAGAAAEgCQAEgCABgFQACgEAAgJQAAgIgCgEQgBgFgEgCQgEgCgGAAQgGAAgDACg");
	this.shape_38.setTransform(-50.05,544.525);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#666666").s().p("AAhAqIgDhJIgCAAIgTA7QgBAEgDAAIgJAAQgEAAgBgEIgSg7IgDAAIgCBJIgLAAIADhOQAAgFAFABIAMAAQADAAABADIAQAyIACAHIABAEIABAAIABgFIACgGIAPgyQABgDAEAAIAMAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIABADIAEBOg");
	this.shape_39.setTransform(-58.675,543.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22,p:{x:-69.175}},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10,p:{x:-0.35}},{t:this.shape_9,p:{x:5.575}},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).to({state:[{t:this.shape_39},{t:this.shape_38},{t:this.shape_9,p:{x:-43.875}},{t:this.shape_10,p:{x:-38.6}},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_22,p:{x:-15.125}},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31}]},127).wait(141));

	// Layer_12
	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f().s("#003E74").ss(1,2,0,3).p("AIku/IAACJIiJAAIAACKIiJAAIiJAAIAACJIAACJIAACJIiJAAIAACJIAACIIAACJIiHAAIiJAAIiKAAIAACJIAACJIAACJIAACKIiJAAIAAiKIAAiJIAAiJIAAiJIAAiJIAAiIIAAiJIAAiJIAAiJIAAiJIAAiKIAAiJIAAiJICJAAICKAAICJAAIAACJIAACJIiJAAIiKAAIAACKIAACJIiJAAAGbu/IAACJIiJAAIiJAAIiJAAIiHAAIAACKIiJAAIAACJIAACJIiKAAIiJAAAGbxIICJAAIAACJIiJAAIiJAAIAACJIAACKIAACJIiJAAIiJAAIAACJIiHAAIiJAAIAACJIAACJIiKAAIAACIIAACJIiJAAAGbxIIAACJAIkmaIiJAAIAACJIAACJIiJAAIAACIIAACJIiJAAIiJAAIAACJIAACJIAACJIAACKIiHAAIiJAAIiKAAIAACJIAACJIAACJIiJAAIAAiJIAAiJAIkojIiJAAIiJAAIAACJIiJAAIiJAAIAACJIiHAAIiJAAIiKAAIAACJIiJAAAIkqsIiJAAIAACJIAACJIiJAAIAACJIiJAAIAACJIAACIIiJAAIiHAAIiJAAIAACJIAACJIAACJIAACJIAACKIAACJIiKAAIiJAAIAAiJAIkojIAACJIAACJIAACJIiJAAIAACIIAACJIAACJIAACJIAACJIAACKIAACJIiJAAIiJAAIiJAAIAACJIAACJIiHAAIiJAAIiKAAAIkqsIAACJAIks2IAACKAIkAAIAACJIiJAAIiJAAIAACJIAACJIiJAAIAACJIAACKIAACJIAACJIAACJIiJAAAIkAAIiJAAIiJAAIiJAAIAACJIAACJIAACJIiJAAIiHAAIiJAAIiKAAIiJAAAIkkRIiJAAIiJAAIAACJIiJAAIiJAAIiHAAIiJAAIAACIIiKAAIiJAAAIkiIIAACIAIkESIAACJIiJAAIiJAAIAACJIAACKIiJAAIiJAAIAACJIiHAAIiJAAIAACJIiKAAIiJAAAIkIkIAACKIiJAAIiJAAIAACJIAACJIiJAAIiJAAIiHAAIiJAAIAACJAIkIkIiJAAIiJAAIiJAAIiJAAIiHAAIiJAAIiKAAIiJAAAIkGbIAACJAIkESIiJAAIiJAAIiJAAIiJAAIiHAAIiJAAIiKAAIiJAAAIkCJIAACJAIkPAIAACJIiJAAIiJAAIiJAAAIkPAIiJAAIiJAAIAACJAIkM3IiJAAIAACJIAACJAIkM3IAACJAIkKuIAACJACJxIICJAAIAACJIiJAAIAACJIAACKIiJAAIAACJIiHAAIiJAAIiKAAIAACJIAACJIiJAAAAAu/IAACJIAACKIiHAAIAACJIAACJIAACJIAACJIAACIIAACJIAACJIAACJIAACJIAACKIAACJIAACJIAACJAAAxIICJAAIAACJIiJAAIiHAAIiJAAIAACJIAACKIiKAAIiJAAAAAxIIAACJAmau/IAACJIiJAAAkQu/IiKAAIiJAAAmaxIIAACJAkQxIIAACJAiHxIICHAAAESxIICJAA");
	this.shape_40.setTransform(-30.675,424.075);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("rgba(0,62,116,0.4)").s().p("AGbRJIAAiJICJAAIAACJgAGbRJIiJAAIAAiJICJAAIAACJgAESRJIiJAAIAAiJIiJAAIAAiJICJAAIAACJIAAiJICJAAIAACJIAAiJIAAiJICJAAIAACJIiJAAICJAAIAACJIiJAAIiJAAICJAAIAACJgAAARJIAAiJIiHAAICHAAIAACJIiHAAIAAiJIAAiJICHAAIAACJICJAAIAACJgAiHRJIiJAAIAAiJICJAAIAACJgAkQRJIiKAAIAAiJIiJAAICJAAIAACJIiJAAIAAiJIAAiJIAAiJIAAiKIAAiJIAAiJIAAiJIAAiJIAAiIIAAiJICJAAIAACJIiJAAICJAAIAACIIiJAAICJAAIAACJIiJAAICJAAIAACJIiJAAICJAAIAACJIiJAAICJAAIAACJIiJAAICJAAIAACKICKAAIiKAAIAAiKIAAiJICKAAIAACJIiKAAICKAAIAACKICJAAIiJAAIAAiKIAAiJIiKAAIAAiJIAAiJICKAAIAACJIAAiJICJAAIAACJIiJAAIiKAAICKAAIAACJICJAAIiJAAIAAiJICJAAIAACJIAACJIiJAAICJAAIAACKICHAAIiHAAIAAiKICHAAIAACKICJAAICJAAIiJAAIAAiKIAAiJIiJAAIAAiJIAAiJICJAAIAACJIiJAAICJAAIAACJICJAAIAAiJIAAiJICJAAIAACJIiJAAICJAAIAACJIiJAAICJAAIAACJIAAiJICJAAIAACJIiJAAICJAAIAACKIiJAAIAAiKIiJAAIAAiJIAACJIiJAAICJAAIAACKIAAiKICJAAIAACKICJAAIAACJIiJAAIAAiJIiJAAIAACJIiJAAIAAiJIAACJIiJAAIAAiJIAACJIiHAAIAAiJIAACJIiJAAIAAiJIAACJIiKAAIAAiJIiJAAICJAAIAACJIiJAAICJAAIAACJICKAAIAACJgAGbPAIAAiJICJAAIAACJgAGbPAgACJPAgAkQPAIAAiJICJAAIAACJgAkQPAgAkQPAIiKAAIAAiJICKAAIAACJgAkQPAgAmaPAgAGbM3gAESM3gACJM3gAAAM3gAkQM3gAmaM3gAGbKugACJKugACJKuIiJAAIAAiKIiHAAIAAiJICHAAIAACJIAAiJIiHAAIAAiJIAAiJICHAAIAACJIiHAAICHAAIAACJICJAAIAACJIiJAAICJAAIAACKgAmaIkgAGbGbIAAiJICJAAIAACJgAGbGbgAGbGbgACJGbIAAiJIAAiJICJAAIAAiJICJAAIAACJICJAAIAACJIiJAAIAAiJIiJAAIAACJIiJAAICJAAIAACJgAmaGbgAGbESgAAAESgAmaESgAIkCJIiJAAIAAiJICJAAIAACJgAGbCJgACJCJIAAiJICJAAIAACJgACJCJgACJCJIiJAAIAAiJICJAAIAACJgAAACJgAAACJIiHAAIAAiJICHAAIAACJgAiHCJgAiHCJIiJAAIAAiJIiKAAIAAiIICKAAIiKAAIAAiJICKAAIAACJIAACIIAAiIIAAiJIiKAAIAAiJIiJAAIAAiJIAAiJIAAiKIAAiJIAAiJICJAAICKAAICJAAICHAAICJAAICJAAICJAAICJAAIAACJIiJAAIAAiJIAACJIiJAAIAAiJIAACJIiJAAIAAiJIAACJICJAAIAACJIiJAAIAAiJIiJAAIAAiJIAACJICJAAIAACJIiJAAIAAiJIiHAAICHAAIAACJIiHAAICHAAIAACKIiHAAIAAiKIAACKIiJAAIAAiKICJAAIAAiJIAAiJIAACJIiJAAIAAiJIAACJIiKAAIAAiJIAACJICKAAIAACJIiKAAICKAAIAACKIiKAAIAAiKIAAiJIiJAAICJAAIAACJIiJAAICJAAIAACKIiJAAICJAAIAACJIiJAAICJAAIAACJICKAAICJAAICHAAIAAiJICJAAIAACJIAAiJIAAiJICJAAIAACJIiJAAICJAAIAACJIiJAAIiJAAICJAAICJAAIAAiJIAAiJIAAiKICJAAIAACKIiJAAICJAAIAACJIiJAAICJAAIAACJIAAiJIAAiJICJAAIAACJIiJAAICJAAIAACJIiJAAICJAAIAACJIiJAAICJAAIAACJIiJAAIiJAAICJAAIAACIIiJAAIAAiIIAAiJICJAAIAACJIAAiJIAAiJIiJAAIAACJIAAiJICJAAIAACJIiJAAIiJAAIiJAAIiHAAIAAiJIAACJIiJAAIAAiJIAACJICJAAIAACJIiJAAICJAAIAACIIiJAAICJAAIAACJgACJkRIAAiJgAAAkRIAAiJgAkQCJIiKAAIAAiJICKAAIAACJgAmaCJgAmaCJgAGbAAIAAiIICJAAIAACIgACJAAIAAiIICJAAIAACIgACJAAgAAAAAIAAiIICJAAIAACIgACJAAgAiHAAIAAiIICHAAIAACIgAiHAAgAmaAAgAESiIIiJAAIAAiJICJAAIAACJgAAAiIIAAiJICJAAIAACJgAiHiIIAAiJICHAAIAACJgAiHiIgAmaiIgAAAkRgAiHkRgAkQkRgAmakRgAojkRIAAiJICJAAIAACJgAiHmaIAAiJICHAAIAACJgAiHmagAiHmaIiJAAIAAiJICJAAIAACJgAkQmaIiKAAIAAiJICKAAIAACJgAmamagAGbojgAAAojIAAiJICJAAIAACJgAAAojgAAAojgAiHojIAAiJICHAAIAACJgAAAojgAiHojgAiHojIiJAAIAAiJICJAAIAACJgAkQojIiKAAIAAiJICKAAIAACJgAmaojgAmaojgAGbqsIAAiKIiJAAIAAiJICJAAIAACJIAAiJICJAAIAACJIiJAAICJAAIAACKgAGbqsgAGbqsgACJqsIAAiKIAACKIiJAAIAAiKICJAAICJAAIAACKgAmaqsgAkQs2IAAiJICJAAIAACJgAmas2gAIku/gAESu/gACJu/gAkQu/gAmau/g");
	this.shape_41.setTransform(-30.675,424.075);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f().s("#003E74").ss(1,2,0,3).p("AIku/IAACJIiJAAIAACKIiJAAIiJAAIAACJIAACJIiJAAIiHAAIiJAAIiKAAIiJAAIAAiJIAAiJIAAiKIAAiJIAAiJICJAAICKAAIAACJIAACJIiKAAIAACKIAACJIAACJIAACJIAACJIAACIIAACJIAACJIAACJIAACJIAACKIiJAAIAAiKIAAiJIAAiJIAAiJIAAiJIAAiIIAAiJIAAiJAGbu/IAACJIiJAAIiJAAIiJAAIiHAAIAACKIiJAAIAACJIiKAAIiJAAAGbxIICJAAIAACJIiJAAIiJAAIAACJIAACKIAACJIiJAAIiJAAIAACJIAACJIAACJIAACIIAACJIiHAAIiJAAIiKAAIiJAAAGbxIIAACJAIkmaIiJAAIAACJIAACJIiJAAIAACIIiJAAIAACJIiJAAIAACJIAACJIAACJIAACKIiHAAIiJAAIiKAAIAACJIiJAAIAAiJAIkojIiJAAIiJAAIAACJIiJAAIAACJIiJAAIiHAAIiJAAIAACJIiKAAIiJAAAIkqsIiJAAIAACJIAACJIiJAAIAACJIiJAAIAACJIAACIIiJAAIiHAAIAACJIAACJIiJAAIAACJIAACJIAACKIAACJIAACJIAACJIiKAAIiJAAIAAiJIAAiJAIkojIAACJIAACJIAACJIiJAAIAACIIAACJIAACJIAACJIAACJIAACKIAACJIiJAAIiJAAIAACJIiJAAIAACJIiHAAIiJAAAIkqsIAACJAIks2IAACKAIkAAIAACJIiJAAIiJAAIiJAAIAACJIAACJIAACJIAACKIiJAAIAACJIAACJIiHAAIiJAAIiKAAIAACJAIkkRIiJAAIiJAAIAACJIiJAAIiJAAIiHAAIiJAAIAACIIAACJIAACJIiKAAIiJAAAIkiIIAACIIiJAAIiJAAIAACJIAACJIAACJIiJAAIiJAAIiHAAIiJAAIiKAAIiJAAAIkESIAACJIAACJIAACKIiJAAIiJAAIiJAAIAACJIiJAAIiHAAIiJAAIiKAAIAACJIiJAAAIkESIiJAAIiJAAIiJAAIiJAAIiHAAIAACJIAACJIiJAAIiKAAIiJAAAIkGbIiJAAIiJAAIAACJIiJAAIiJAAIiHAAIAACKIAACJIAACJIAACJAIkIkIiJAAIiJAAIAACKIAACJIAACJIiJAAIAACJIiJAAAIkCJIAACJAIkPAIAACJIiJAAIiJAAIiJAAAIkPAIiJAAIiJAAIAACJAIkM3IiJAAIAACJIAACJAIkM3IAACJAIkKuIAACJACJxIICJAAIAACJIiJAAIAACJIAACKIiJAAIAACJIiHAAIiJAAIAACJIAACJIiKAAIiJAAAAAu/IAACJIAACKIiHAAIAACJIAACJIAACJIAACJIAACIIiJAAIiKAAIiJAAAAAxIICJAAIAACJIiJAAIiHAAIAACJIiJAAIAACKIiKAAIiJAAAAAxIIAACJAkQxIICJAAIAACJIiJAAIiKAAIAACJIiJAAAmaxIIAACJIiJAAAiHxIICHAAAESxIICJAA");
	this.shape_42.setTransform(-30.675,424.075);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("rgba(0,62,116,0.4)").s().p("AGbRJIAAiJICJAAIAACJgAESRJIAAiJICJAAIAACJgAESRJIiJAAIAAiJIAACJIiJAAIAAiJICJAAICJAAIAACJgAAARJIiHAAIAAiJICHAAIAACJgAiHRJIiJAAIAAiJICJAAIAACJgAkQRJIiKAAIAAiJIiJAAICJAAIAACJIiJAAIAAiJIAAiJIAAiJIAAiKIAAiJIAAiJIAAiJIAAiJIAAiIIAAiJICJAAIAACJIiJAAICJAAIAACIIiJAAICJAAIAACJIiJAAICJAAIAACJIiJAAICJAAIAACJIiJAAICJAAIAACJIiJAAICJAAIAACKICKAAICJAAIiJAAIAAiKIAAiJIiKAAIAAiJIAAiJICKAAIAACJIAAiJICJAAIAACJIiJAAIiKAAICKAAIAACJICJAAIiJAAIAAiJICJAAIAACJIAACJIiJAAICJAAIAACKICHAAIiHAAIAAiKICHAAIAACKICJAAIiJAAIAAiKIiHAAIAAiJICHAAIAACJIAAiJIiHAAIAAiJIAAiJICHAAIAACJIiHAAICHAAIAACJICJAAIAACJIiJAAICJAAIAACKIAAiKIAAiJIiJAAIAAiJIAAiJICJAAIiJAAIAAiJICJAAIAAiIICJAAIAAiJICJAAIAACJIiJAAICJAAIAACIICJAAIAACJIiJAAIAAiJIiJAAIAAiIIAACIIiJAAIAACJIAACJIiJAAICJAAIAACJICJAAIAAiJIAAiJIAAiJICJAAIAACJICJAAIAACJIiJAAIAAiJIiJAAICJAAIAACJIiJAAICJAAIAACJICJAAIAACJIiJAAIAAiJIiJAAIAACJIiJAAICJAAIAACKIiJAAICJAAIAAiKIAAiJICJAAIAACJIiJAAICJAAIAACKICJAAIAACJIiJAAIAAiJIiJAAIAACJIiJAAIAAiJIAACJIiJAAIAAiJIAACJIiHAAIAAiJIAACJICHAAIAACJIiHAAIAAiJIiJAAIAAiJIAACJIiKAAIAAiJIiJAAICJAAIAACJIiJAAICJAAIAACJICKAAIAACJgAGbPAIAAiJICJAAIAACJgAGbPAgAESPAIAAiJIAAiJICJAAIAACJIiJAAICJAAIAACJgAESPAgAESPAIiJAAIAAiJICJAAIAACJgAAAPAIAAiJICJAAIAACJgAiHPAIiJAAIAAiJICJAAIAACJgAkQPAIiKAAIAAiJICKAAIAACJgAkQPAgAmaPAgAGbM3gAGbM3gACJM3gAAAM3gAAAM3gAiHM3gAkQM3gAmaM3gAmaM3gAGbKuIAAiKICJAAIAACKgAGbKugAkQKugAkQKuIiKAAIAAiKIAAiJICKAAIAACJIiKAAICKAAIAACKgAGbIkgAGbIkgAmaIkgAGbGbIAAiJICJAAIAACJgACJGbIAAiJIAAiJIAAiJICJAAIAACJIiJAAICJAAIAACJIiJAAICJAAIAACJgAmaGbgAGbESgAAAESgAmaESgAGbCJgAiHCJIAAiJICHAAIAACJgAiHCJgAiHCJIiJAAIAAiJICJAAIAACJgAkQCJgAkQCJIiKAAIAAiJICKAAIAACJgAmaCJgAmaCJgAGbAAIAAiIICJAAIAACIgAAAAAIAAiIICJAAIAACIgAiHAAIAAiIICHAAIAACIgAkQAAIAAiIIiKAAIAAiJICKAAIAACJICJAAIAACIgAmaAAIAAiIICKAAIAACIgAmaAAgAmaAAgAGbiIIAAiJICJAAIAACJgAGbiIgAGbiIgACJiIIAAiJICJAAIAACJgAAAiIIAAiJICJAAIAACJgAiHiIIAAiJICHAAIAACJgAiHiIgAiHiIIiJAAIAAiJIiKAAIAAiJIiJAAIAAiJIAAiJIAAiKIAAiJIAAiJICJAAICKAAICJAAICHAAICJAAIAACJIiJAAIAAiJIAACJIiHAAICHAAIAACJIiHAAICHAAIAACKIiHAAIAAiKIAACKIiJAAIAAiKICJAAIAAiJIAAiJIAACJIiJAAIAAiJIAACJIiKAAIAAiJIAACJICKAAIAACJIAACKIiKAAIAAiKICKAAIiKAAIAAiJIiJAAICJAAIAACJIiJAAICJAAIAACKIiJAAICJAAIAACJICKAAIAACJIiKAAIAAiJIiJAAICJAAIAACJICKAAICJAAICHAAICJAAICJAAIAACJIiJAAIAAiJIAACJIiJAAIiHAAIAAiJIAACJIiJAAIAAiJIAACJICJAAIAACJgAAAkRIAAiJgAmaiIgAmaiIgAGbkRIAAiJIiJAAICJAAIAACJIiJAAIAAiJIAAiJIiJAAIAAiJICJAAIAACJIAAiJIAAiKICJAAIAACKIiJAAICJAAIAACJIiJAAICJAAIAACJIAAiJIAAiJICJAAIAACJIiJAAICJAAIAACJIiJAAICJAAIAACJgACJkRgAAAkRgAiHkRgAmakRgAojkRIAAiJICJAAIAACJgAESmaIiJAAIAAiJICJAAIAACJgAAAmaIAAiJICJAAIAACJgACJmagAAAmaIiHAAIAAiJICHAAIAACJgAiHmagAiHmaIiJAAIAAiJIiKAAIAAiJICKAAIAACJICJAAIAACJgAGbojgAAAojIAAiJICJAAIAACJgAAAojgAAAojIiHAAIAAiJICHAAIAACJgAiHojgAiHojIiJAAIAAiJICJAAIAACJgAmaojgAmaojgAGbqsIAAiKIiJAAIAAiJIiJAAICJAAIAACJIiJAAIAAiJIAACJIiJAAIAAiJICJAAIAAiJICJAAICJAAICJAAIAACJIiJAAIAAiJIAACJIiJAAIAAiJIAACJICJAAIAACJIAAiJICJAAIAACJIiJAAICJAAIAACKgAGbqsgAGbqsgACJqsIAAiKICJAAIAACKgACJqsIiJAAIAAiKICJAAIAACKgAmaqsgACJs2gAAAs2gAkQs2IAAiJICJAAIAACJgAmas2gAIku/gAESu/gAESu/gAAAu/gAmau/gAmau/g");
	this.shape_43.setTransform(-30.675,424.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40}]}).to({state:[{t:this.shape_43},{t:this.shape_42}]},127).wait(141));

	// Layer_4
	this.instance = new lib.Symbol4();
	this.instance.setTransform(-411.6,264.2,1,1,0,0,0,11.2,11.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({guide:{path:[-411.6,264.2,-404.2,240.7,-396.9,217.3,-347.2,152.2,-297.6,87.2,-183.2,87.2,-68.8,87.2]}},267).wait(1));

	// Layer_3 copy
	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f().s("#FF0000").ss(1,1,1).p("Aayt1MgjwAAAIvhUVIiSHW");
	this.shape_44.setTransform(-240.225,175.625);

	this.timeline.addTween(cjs.Tween.get(this.shape_44).wait(268));

	// Layer_2
	this.instance_1 = new lib.Symbol4();
	this.instance_1.setTransform(2.25,264.2,1,1,0,0,0,11.2,11.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({guide:{path:[2.4,264.2,29.9,175.6,57.5,87.1,86.9,87.1,116.3,87.1,224.4,200.4,348.3,212.2]}},267).wait(1));

	// Layer_3 copy
	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f().s("#FF0000").ss(1,1,1,3,true).p("A7BN2IIn7rIJMAAQQ5RtTXB2");
	this.shape_45.setTransform(175.275,175.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_45).wait(268));

	// Layer_10
	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FF0000").s().p("AYoN/IAAgCIAAg8IAAgCIACAAIACAAIAAACIAAA8IAAACIgCABIgCgBgA4lNRIgBgCIAAg8IABgBIACgBIABABIABABIAAA8IgBACIgBABIgCgBgEAoEANRIgBgCIAAg8IABgCIACgBIACABIABACIAAA8IgBACIgCAAIgCAAgEgoHAM+IgBgBIAAg8IABgCIACgBIACABIABACIAAA8IgBABIgCABIgCgBgAYoMHIAAgCIAAg8IAAgBIACgBIACABIAAABIAAA8IAAACIgCABIgCgBgA4lLZIgBgCIAAg8IABgBIACgBIABABIABABIAAA8IgBACIgBABIgCgBgEAoEALZIgBgCIAAg8IABgCIACgBIACABIABACIAAA8IgBACIgCAAIgCAAgEgoHALHIgBgCIAAg8IABgCIACgBIACABIABACIAAA8IgBACIgCAAIgCAAgAYoKPIAAgCIAAg8IAAgCIACAAIACAAIAAACIAAA8IAAACIgCABIgCgBgA4lJhIgBgCIAAg8IABgCIACAAIABAAIABACIAAA8IgBACIgBABIgCgBgEAoEAJgIgBgBIAAg8IABgCIACgBIACABIABACIAAA8IgBABIgCABIgCgBgEgoHAJOIgBgBIAAg8IABgCIACgBIACABIABACIAAA8IgBABIgCABIgCgBgAYoIXIAAgCIAAg8IAAgCIACAAIACAAIAAACIAAA8IAAACIgCABIgCgBgA4lHpIgBgCIAAg8IABgBIACgBIABABIABABIAAA8IgBACIgBABIgCgBgEAoEAHoIgBgBIAAg8IABgCIACgBIACABIABACIAAA8IgBABIgCABIgCgBgEgoHAHXIgBgCIAAg8IABgCIACgBIACABIABACIAAA8IgBACIgCAAIgCAAgAYoGfIAAgCIAAgWIAAgCIACgBIACABIAAACIAAAWIAAACIgCABIgCgBgA4lFxIgBgCIAAg8IABgBIACgBIABABIABABIAAA8IgBACIgBABIgCgBgEAoEAFxIgBgCIAAg8IABgCIACgBIACABIABACIAAA8IgBACIgCAAIgCAAgA4lD5IgBgCIAAg8IABgCIACAAIABAAIABACIAAA8IgBACIgBABIgCgBgEAoEAD4IgBgBIAAg8IABgCIACgBIACABIABACIAAA8IgBABIgCABIgCgBgA4lCBIgBgCIAAg8IABgBIACgBIABABIABABIAAA8IgBACIgBABIgCgBgEAoEACAIgBgBIAAg8IABgCIACgBIACABIABACIAAA8IgBABIgCABIgCgBgA4lAJIgBgCIAAg7IABgBIACgBIABABIABABIAAA7IgBACIgBABIgCgBgEAoEAAJIgBgCIAAg7IABgCIACgBIACABIABACIAAA7IgBACIgCAAIgCAAgA4lhuIgBgCIAAg8IABgCIACAAIABAAIABACIAAA8IgBACIgBABIgCgBgEAoEgBvIgBgBIAAg8IABgCIACgBIACABIABACIAAA8IgBABIgCABIgCgBgA4ljmIgBgCIAAg8IABgBIACgBIABABIABABIAAA8IgBACIgBABIgCgBgEAoEgDnIgBgBIAAg8IABgCIACgBIACABIABACIAAA8IgBABIgCABIgCgBgA4lleIgBgCIAAg8IABgBIACgBIABABIABABIAAA8IgBACIgBABIgCgBgEAoEgFeIgBgCIAAg8IABgCIACgBIACABIABACIAAA8IgBACIgCAAIgCAAgA4lnWIgBgCIAAg8IABgCIACAAIABAAIABACIAAA8IgBACIgBABIgCgBgEAoEgHXIgBgBIAAg8IABgCIACgBIACABIABACIAAA8IgBABIgCABIgCgBgA4lpOIgBgCIAAg8IABgCIACAAIABAAIABACIAAA8IgBACIgBABIgCgBgEAoEgJPIgBgBIAAg8IABgCIACgBIACABIABACIAAA8IgBABIgCABIgCgBgA4lrGIgBgCIAAg8IABgBIACgBIABABIABABIAAA8IgBACIgBABIgCgBgEAoEgLGIgBgCIAAg8IABgCIACgBIACABIABACIAAA8IgBACIgCAAIgCAAgA4ls+IgBgCIAAg8IABgCIACAAIABAAIABACIAAA8IgBACIgBABIgCgBgEAoEgM/IgBgBIAAg8IABgCIACgBIACABIABACIAAA8IgBABIgCABIgCgBg");
	this.shape_46.setTransform(-140.4,176.375);

	this.timeline.addTween(cjs.Tween.get(this.shape_46).wait(268));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-416.6,78.8,770,473.09999999999997);


// stage content:
(lib.retrofit_2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		// Enable touch events while allowing the touch events to bubble up to the document.
		
		createjs.Touch.enable(stage, false, true);
		
		// Don't let the stage to automatically prevent default touch events.
		
		stage.preventSelection = false;
		
		this.graph1.stop()
		this.button.on("mousedown", function (e)
		
			{
		
				e.target.offsetX = (e.stageX / stage.scaleX) - e.target.x;
		
			}.bind(this));
		
		this.button.on("pressmove", function (e)
		
			{
		
				e.target.x = this.clamp((e.stageX / stage.scaleX) - e.target.offsetX, this.bar.x, this.bar.x + this.bar.nominalBounds.width);
		
				this.setProportion();
				this.controlTower1();
		
			}.bind(this));
		
		this.setProportion = function ()
		
		{
			var prop = (this.button.x - this.bar.x) / this.bar.nominalBounds.width;
			this.txt.x = this.button.x;
			this.txt.text = Math.round(prop * 100) + "%";
			this.graph1.gotoAndStop(Math.floor(this.graph1.timeline.duration * prop))
		}.bind(this);
		
		this.clamp = function (value, min, max)
		
		{
		
			if (value < min)
		
				return min;
		
			else if (value > max)
		
				return max;
		
			else
		
				return value;
		
		}
		
		setTimeout(this.setProportion, 0);
		
		
		
		//buttons
		this.tallBBtn.txt.text = "hide";
		this.tallBBtn.addEventListener("click", tallBBtnfunction.bind(this));
		
		
		//create function to start/stop animation and toggle button text
		function tallBBtnfunction() {
			if (this.tallBBtn.txt.text == "hide") {
				this.tallBBtn.txt.text = "show";
				this.graph1.visible = false;
			} else {
		
				this.tallBBtn.txt.text = "hide";
				this.graph1.visible = true;
			}
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// JS
	this.graph1 = new lib.Symbol22();
	this.graph1.name = "graph1";
	this.graph1.setTransform(392.3,98.3,0.5636,0.5636,0,0,0,174.8,132.3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAAAGQAAAAAAAAQAAAAgBAAQAAAAAAgBQgBAAAAgBQgCgCABgDQABgEACgBQAAAAAAABQABAAABAAQAAAAABABQAAAAABAAIABAFQAAABAAAAQgBABAAAAQAAABAAAAQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAABAAAAIgBgBg");
	this.shape.setTransform(116.7357,48.0042);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.graph1}]}).wait(1));

	// Bar
	this.txt = new cjs.Text("38%", "8px 'Helvetica'", "#666666");
	this.txt.name = "txt";
	this.txt.lineHeight = 13;
	this.txt.lineWidth = 38;
	this.txt.parent = this;
	this.txt.setTransform(16.8,345);

	this.button = new lib.SliderButton();
	this.button.name = "button";
	this.button.setTransform(19.9,411.1);
	new cjs.ButtonHelper(this.button, 0, 1, 2, false, new lib.SliderButton(), 3);

	this.bar = new lib.SliderBar();
	this.bar.name = "bar";
	this.bar.setTransform(19.8,367.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.bar},{t:this.button},{t:this.txt}]}).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003E74").s().p("AgKAOIAPgFIAEgBIAAgBIgEgBIgNgDIgCAAIAAgBIAAgDIAAgBIACAAIANgEIACAAIACAAIAAgBIgCgBIgCAAIgPgEIAAgFIAUAHIABAAIAAABIAAAEIAAABIgBABIgOADIgCAAIgBAAIAAAAIABAAIACABIAOAEIABAAIAAABIAAADIAAACIgBAAIgUAGg");
	this.shape_1.setTransform(286.3,148.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003E74").s().p("AgFAJQgDgBgCgCIgBgGIABgFIAFgDIAFgBIAHABQABAAAAAAQABABAAAAQABAAAAABQAAAAABABIABAFIgBAGQgBAAAAABQAAAAgBABQAAAAgBABQAAAAgBAAIgHABIgFgBgAgEgFQAAAAgBABQAAAAgBAAQAAAAAAABQAAAAAAAAIgBADIABAEQAAAAAAAAQAAABAAAAQABAAAAAAQABABAAAAIAEAAIAFAAQABAAAAgBQAAAAABAAQAAAAAAgBQAAAAAAAAIACgEIgCgDQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAgBgBAAIgFAAIgEAAg");
	this.shape_2.setTransform(286.3,151.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003E74").s().p("AgOAJIAAgEIAXAAIADAAIAAgDIAAgKIADAAIAAALQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAg");
	this.shape_3.setTransform(285.85,153.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#003E74").s().p("AgQgGIAAgDIAhAQIAAAEg");
	this.shape_4.setTransform(286,157.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#003E74").s().p("AgPAFIAAgEIAZAAIACgBIABgBIAAgCIACgBIAAACIABACQAAAAAAAAQAAABAAABQgBAAAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_5.setTransform(285.85,159.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#003E74").s().p("AgPAFIAAgEIAZAAIACgBIABgBIAAgCIACgBIAAACIABACQAAAAAAAAQAAABAAABQgBAAAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_6.setTransform(285.85,161.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#003E74").s().p("AADAJQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgBAAgBIAAgIIgCAAIgCABIgBAEIABAJIgEAAIgBgKQAAgEACgCQACgBADAAIAPAAIAAACIgEABIADAEIACAEQgBADgBACQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAgAABADIAAACIACABIACAAIACgBIABgDIgBgCIgCgFIgEAAg");
	this.shape_7.setTransform(286.3,163.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#003E74").s().p("AgKAQIAAgDIAEAAIgDgFIgBgEQAAgEAEgBQgEgEAAgEQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAQABAAAAAAQABAAABAAIAPAAIAAADIgOAAIgDABIgBADIABADIACAEIAPAAIAAADIgOAAIgDABIgBACIABADIACAEIAPAAIAAAEg");
	this.shape_8.setTransform(286.275,166.475);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#003E74").s().p("AgNAJIgBgDIgBgGIABgIIACAAIAAAIIAAAEIACACIADAAIADgBIACgDIACgFQAAgDACgCQACgBADAAIAGABIACADIABAFIgBAKIgCAAIAAgEIAAgFIgBgDIgBgDIgEAAIgDAAIgBABIAAADIgCAFQgBADgBACQgDABgDAAIgGgBg");
	this.shape_9.setTransform(285.85,169.675);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#003E74").s().p("AgPAKIAAgEIAJAAIAEAAIgDgFIgBgEQAAAAAAgBQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAAAIAQAAIAAAEIgQAAIgCABIAAACIAAADIACAFIAQAAIAAAEg");
	this.shape_10.setTransform(285.725,31.575);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#003E74").s().p("AAGALIgCgEIgCABIgBABIgBgBIgCgBIgCACIgEABIgEgBIgCgDIgBgFIABgEIAAgHIACAAIAAAEIAEgCQAEABACACQABACAAAEIAAAEIABABIABgBIABgBIABgHQAAgBAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAABgBQAAAAABAAQABAAAAAAIAEABQABAAAAABQAAAAABAAQAAABAAAAQAAABAAABIABAEIgBAHIgCADIgEABIgDAAgAAGgEIAAACIgBAHIACACIACAAIACAAIABgCIABgFIgBgDIgBgBIgCgBIgCAAIgBABgAgLgDIgBAEIABAEIADABIADgBIABgEQAAgBAAAAQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAIgDABg");
	this.shape_11.setTransform(286.625,34.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#003E74").s().p("AgFACIAAgDIAVAAIAAADgAgNACIgBgBIgBAAIAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIACAAIABABIAAABIgBABg");
	this.shape_12.setTransform(285.725,35.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#003E74").s().p("AgOALIAAgEIAMAAIAAgNIgMAAIAAgEIAdAAIAAAEIgOAAIAAANIAOAAIAAAEg");
	this.shape_13.setTransform(285.75,37.95);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#003E74").s().p("AgQgGIAAgDIAhAQIAAAEg");
	this.shape_14.setTransform(285.9,41.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#003E74").s().p("AgGAJQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBgBAAIgBgGQAAgEACgCQACgDADAAQADAAACACQAAAAAAAAQAAABABAAQAAABAAAAQAAABAAABIAAAJIAEgBIACgCIAAgDIAAgIIADAAIAAAEIABAEIgBAFQgCADgDABIgGABIgGgBgAgGgEIgBAEIABADIACACIAEABIAAgIQAAgBAAAAQAAgBgBAAQAAAAgBgBQgBAAgBAAIgCABg");
	this.shape_15.setTransform(286.2,44.925);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#003E74").s().p("AAGALIgCgEIgCACIgBAAIgBAAIgCgCIgCADIgEAAIgEAAIgCgEIgBgFIABgEIAAgHIACAAIAAAEIAEgBQAEAAACACQABACAAAEIAAAEIABABIABgBIABgBIABgIQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAIAEABQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIABAGIgBAGIgCADIgEABIgDAAgAAGgEIAAACIgBAHIACACIACAAIACAAIABgCIABgEIgBgEIgBgCIgCAAIgCAAIgBABgAgLgDIgBAEIABAEIADABIADgBIABgEQAAgBAAAAQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAIgDABg");
	this.shape_16.setTransform(286.625,47.35);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#003E74").s().p("AgKAHIAAgDIAEAAQgEgEAAgFIAAgBIADABIAAABIABADIACAEIAPAAIAAAEg");
	this.shape_17.setTransform(286.175,49.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#003E74").s().p("AADAJQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgBAAgBIAAgIIgCAAIgCABIgBAEIABAJIgEAAIgBgKQABgEABgCQACgBADAAIAPAAIAAACIgEABIADAEIACAEQgBADgBACQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAgAABADIAAACIADABIABAAIACgBIABgDIgBgCIgCgFIgEAAg");
	this.shape_18.setTransform(286.2,51.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#003E74").s().p("AgOAJIAAgDIAXAAIADgBIAAgDIAAgKIADAAIAAALQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAg");
	this.shape_19.setTransform(285.75,53.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#003E74").s().p("AgKAOIAPgFIAEgBIAAgBIgEgBIgNgDIgBAAIgBgBIAAgDIABgBIABAAIANgEIACAAIACAAIAAgBIgBgBIgDAAIgPgEIAAgFIAUAHIABAAIAAABIAAAEIAAABIgBABIgOADIgCAAIgBAAIAAAAIAAAAIADABIAOAEIABAAIAAABIAAADIAAACIgBAAIgUAGg");
	this.shape_20.setTransform(55.65,148.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#003E74").s().p("AgGAJQgCgBgBgCIgBgGIABgFIADgDIAGgBIAHABQABAAAAAAQABABAAAAQABAAAAABQAAAAABABIAAAFIAAAGQgBAAAAABQAAAAgBABQAAAAgBABQAAAAgBAAIgHABIgGgBgAgEgFQAAAAgBABQAAAAgBAAQAAAAAAABQAAAAgBAAIAAADIAAAEQABAAAAAAQAAABAAAAQABAAAAAAQABABAAAAIAEAAIAFAAQABAAAAgBQAAAAABAAQAAAAAAgBQAAAAABAAIABgEIgBgDQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBgBAAIgFAAIgEAAg");
	this.shape_21.setTransform(55.65,151.525);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#003E74").s().p("AgPAJIAAgEIAYAAIACAAIABgDIAAgKIADAAIABALQAAABgBAAQAAABAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAg");
	this.shape_22.setTransform(55.2,153.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#003E74").s().p("AgQgGIAAgDIAhAQIAAAEg");
	this.shape_23.setTransform(55.35,157.25);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#003E74").s().p("AgPAFIAAgEIAZAAIABgBIABgBIAAgCIAEgBIAAACIAAACQAAAAAAAAQAAABAAABQgBAAAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_24.setTransform(55.2,159.875);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#003E74").s().p("AgPAFIAAgEIAZAAIABgBIABgBIAAgCIAEgBIAAACIAAACQAAAAAAAAQAAABAAABQgBAAAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_25.setTransform(55.2,161.225);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#003E74").s().p("AADAJQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAgBIAAgIIgDAAIgDABIAAAEIAAAJIgCAAIgBgKQAAgEABgCQABgBAEAAIAPAAIAAACIgDABIACAEIABAEQABADgCACQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAgAABADIAAACIACABIACAAIADgBIAAgDIAAgCIgDgFIgEAAg");
	this.shape_26.setTransform(55.65,163.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#003E74").s().p("AgKAQIAAgDIAEAAIgDgFIgBgEQAAgEAEgBQgEgEAAgEQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAQABAAAAAAQABAAABAAIAPAAIAAADIgOAAIgDABIgBADIABADIACAEIAPAAIAAADIgOAAIgDABIgBACIABADIACAEIAPAAIAAAEg");
	this.shape_27.setTransform(55.625,166.475);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#003E74").s().p("AgNAJIgCgDIAAgGIABgIIACAAIAAAIIAAAEIACACIADAAIADgBIADgDIABgFQAAgDABgCQADgBAEAAIAFABIADADIAAAFIgBAKIgDAAIAAgEIAAgFIAAgDIgBgDIgDAAIgEAAIgBABIgBADIgBAFQgBADgBACQgCABgEAAIgGgBg");
	this.shape_28.setTransform(55.2,169.675);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#003E74").s().p("AgPAKIAAgEIAJAAIAEAAIgDgFIgBgEQAAAAAAgBQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIAQAAIAAAEIgQAAIgCABIAAACIAAADIACAFIAQAAIAAAEg");
	this.shape_29.setTransform(55.075,31.575);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#003E74").s().p("AAGALIgCgEIgCABIgBABIgBgBIgCgBIgCACIgEABIgEgBIgCgDIgBgFIABgEIAAgHIACAAIAAAEIAEgCQAEABACACQABACAAAEIAAAEIABABIABgBIABgBIABgHQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAIAEABQABAAAAABQAAAAABAAQAAABAAAAQAAABAAABIABAEIgBAHIgCADIgEABIgDAAgAAGgEIAAACIgBAHIACACIACAAIACAAIABgCIABgFIgBgDIgBgBIgCgBIgCAAIgBABgAgLgDIgBAEIABAEIADABIADgBIABgEQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAIgDABg");
	this.shape_30.setTransform(55.975,34.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#003E74").s().p("AgFACIAAgDIAVAAIAAADgAgNACIgBgBIgBAAIAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIACAAIABABIAAABIgBABg");
	this.shape_31.setTransform(55.075,35.95);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#003E74").s().p("AgPALIAAgEIANAAIAAgNIgNAAIAAgEIAeAAIAAAEIgOAAIAAANIAOAAIAAAEg");
	this.shape_32.setTransform(55.1,37.95);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#003E74").s().p("AgQgGIAAgDIAhAQIAAAEg");
	this.shape_33.setTransform(55.25,41.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#003E74").s().p("AgGAJQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAAAIgCgGQABgEACgCQABgDADAAQADAAACACQAAAAAAAAQAAABABAAQAAABAAAAQAAABAAABIAAAJIAEgBIACgCIABgDIgBgIIADAAIAAAEIABAEIgBAFQgCADgDABIgGABIgGgBgAgGgEIgBAEIABADIABACIAFABIAAgIQAAgBAAAAQAAgBgBAAQAAAAgBgBQgBAAgBAAIgCABg");
	this.shape_34.setTransform(55.55,44.925);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#003E74").s().p("AAGALIgCgEIgCACIgBAAIgBAAIgCgCIgCADIgEAAIgEAAIgCgEIgBgFIABgEIAAgHIACAAIAAAEIAEgBQAEAAACACQABACAAAEIAAAEIABABIABgBIABgBIABgIQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAIAEABQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIABAGIgBAGIgCADIgEABIgDAAgAAGgEIAAACIgBAHIACACIACAAIACAAIABgCIABgEIgBgEIgBgCIgCAAIgCAAIgBABgAgLgDIgBAEIABAEIADABIADgBIABgEQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAIgDABg");
	this.shape_35.setTransform(55.975,47.35);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#003E74").s().p("AgKAHIAAgDIAEAAQgEgEAAgFIAAgBIADABIAAABIABADIACAEIAPAAIAAAEg");
	this.shape_36.setTransform(55.525,49.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#003E74").s().p("AADAJQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgBAAgBIAAgIIgCAAIgCABIgBAEIABAJIgDAAIgCgKQAAgEACgCQABgBAEAAIAPAAIAAACIgDABIACAEIACAEQgBADgBACQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAgAABADIAAACIACABIACAAIADgBIAAgDIAAgCIgDgFIgEAAg");
	this.shape_37.setTransform(55.55,51.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#003E74").s().p("AgPAJIAAgDIAYAAIADgBIAAgDIAAgKIADAAIAAALQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAg");
	this.shape_38.setTransform(55.1,53.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#003E74").s().p("AABAOQgEAAgDgBQgDgBgBgEQgBgDAAgFQAAgEABgEQABgDADgBIAGgBQAHAAACACQADACAAAFQAAADgBABQgCACgDAAIgMAAIABAFIADADIAEAAIAJAAIABADIgFABIgGAAgAgDgIQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIgBAGIAKAAQABAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgFgBIgEABg");
	this.shape_39.setTransform(486.825,182.825);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#003E74").s().p("AABAUQgCAAgCgCQgCgBAAgEIAAggIAFAAIAAAfIAAACIADABIACAAIABAFIgCAAg");
	this.shape_40.setTransform(484.625,182.25);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#003E74").s().p("AgFAUIgGgCIAAglIAEAAIAAAKIAAAGQAFgEAEAAQAGAAACADQACADAAAGIgBAJQgBADgDACQgCABgFAAIgFAAgAgCgDIgFADIAAAPIAHABIAEgBIADgDIAAgHIAAgFIgCgDIgEAAIgDAAg");
	this.shape_41.setTransform(482.075,182.25);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#003E74").s().p("AgCAUIAAgbIAFAAIAAAbgAAAgNQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAgDIABgBIABgBIABAAQAAAAABABQAAAAAAAAQAAAAAAAAQABABAAAAIAAADQAAAAgBABQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_42.setTransform(479.7,182.25);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#003E74").s().p("AAJAOIgIgNIgBAAIgHANIgGAAIAJgOIgIgNIAFAAIAHAMIABAAIAGgMIAGAAIgJANIAJAOg");
	this.shape_43.setTransform(477.55,182.825);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#003E74").s().p("AABAOQgEAAgDgBQgDgBgBgEQgBgDAAgFQAAgEABgEQABgDADgBIAGgBQAHAAACACQADACAAAFQAAADgBABQgCACgDAAIgMAAIABAFIADADIAEAAIAJAAIABADIgFABIgGAAgAgDgIQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIgBAGIAKAAQABAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgFgBIgEABg");
	this.shape_44.setTransform(474.575,182.825);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#003E74").s().p("AABAUQgCAAgCgCQgCgBAAgEIAAggIAFAAIAAAfIAAACIADABIACAAIABAFIgCAAg");
	this.shape_45.setTransform(472.425,182.25);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#003E74").s().p("AgLAUIAAggQAAgDACgBQACgDAEAAIAPABIgBAEIgNAAIgDABIgBACIAAAJIAPAAIAAAEIgPAAIAAASg");
	this.shape_46.setTransform(470.025,182.25);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#003E74").s().p("AgEAUIAAgWIgGAAIAAgEIAGAAIAAgFQAAgEACgCQABgCADAAIAIAAIAAAEIgGAAIgEABIAAADIAAAFIAIAAIAAAEIgIAAIAAAWg");
	this.shape_47.setTransform(305.25,180.375);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#003E74").s().p("AgEAUIAAgWIgGAAIAAgEIAGAAIAAgFQAAgEACgCQABgCAEAAIAHAAIAAAEIgGAAIgEABIAAADIAAAFIAIAAIAAAEIgIAAIAAAWg");
	this.shape_48.setTransform(303.1,180.375);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#003E74").s().p("AgBAUIAAgbIADAAIAAAbgAAAgNQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAgDIAAgBIABgBIABAAQAAAAABABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAADQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_49.setTransform(301.2,180.45);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#003E74").s().p("AADASQgDAAgBgCQgCgCAAgDIAAgQIgFAAIAAgDIAFgBIAAgIIAEAAIAAAIIAIAAIAAAEIgIAAIAAAPIAAADIADAAIAEAAIABAFIgDAAg");
	this.shape_50.setTransform(299.475,180.65);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#003E74").s().p("AgLATIAAgEIAEAAIAHAAIAEAAIADgBIABgEIgBgEIgBgCIgDgBIgHgCQgEgBgCgCQgCgCAAgFQAAgEACgCQABgCADgCIAGAAIAMABIgBAEIgLAAIgEAAIgCABIgBAEIABAFIAEABIAHACQAEABACADQACACAAAFIgBAGIgEAEIgIAAIgLgBg");
	this.shape_51.setTransform(296.775,180.45);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#003E74").s().p("AABAOQgEAAgDgBQgDgBgBgEQgBgDAAgFQAAgEABgEQABgDADgBIAGgBQAHAAACACQADACAAAFQAAADgBABQgCACgDAAIgMAAIABAFIADADIAEAAIAJAAIABADIgFABIgGAAgAgDgIQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIgBAGIAKAAQADAAAAgEQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgFgBIgEABg");
	this.shape_52.setTransform(258.175,181.025);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#003E74").s().p("AABAUQgCAAgCgCQgCgBAAgEIAAggIAFAAIAAAfIAAACIADABIACAAIABAFIgCAAg");
	this.shape_53.setTransform(255.975,180.45);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#003E74").s().p("AgFAUIgGgCIAAglIAEAAIAAAKIAAAGQAFgEAEAAQAGAAACADQACADAAAGIgBAJQgBADgDACQgCABgFAAIgFAAgAgCgDIgFADIAAAPIAHABIAEgBIADgDIAAgHIAAgFIgCgDIgEAAIgDAAg");
	this.shape_54.setTransform(253.425,180.45);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#003E74").s().p("AgBAUIAAgbIADAAIAAAbgAAAgNQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAgDIAAgBIABgBIABAAQAAAAABABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAADQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_55.setTransform(251.05,180.45);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#003E74").s().p("AAIAOIgIgNIAAAAIgIANIgEAAIAJgOIgJgNIAFAAIAHAMIAAAAIAIgMIAFAAIgIANIAJAOg");
	this.shape_56.setTransform(248.9,181.025);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#003E74").s().p("AABAOQgEAAgDgBQgDgBgBgEQgBgDAAgFQAAgEABgEQABgDADgBIAGgBQAHAAACACQADACAAAFQAAADgBABQgCACgDAAIgMAAIABAFIADADIAEAAIAJAAIABADIgFABIgGAAgAgDgIQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIgBAGIAKAAQADAAAAgEQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgFgBIgEABg");
	this.shape_57.setTransform(245.925,181.025);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#003E74").s().p("AABAUQgCAAgCgCQgCgBAAgEIAAggIAFAAIAAAfIAAACIADABIACAAIABAFIgCAAg");
	this.shape_58.setTransform(243.775,180.45);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#003E74").s().p("AgLAUIAAggQAAgDACgBQACgDAEAAIAPABIgBAEIgNAAIgDABIgBACIAAAJIAPAAIAAAEIgPAAIAAASg");
	this.shape_59.setTransform(241.375,180.45);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#003E74").s().p("AgEAUIAAgWIgGAAIAAgEIAGAAIAAgFQAAgEACgCQABgCADAAIAIAAIAAAEIgGAAIgEABIAAADIAAAFIAIAAIAAAEIgIAAIAAAWg");
	this.shape_60.setTransform(76.65,178.625);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#003E74").s().p("AgEAUIAAgWIgGAAIAAgEIAGAAIAAgFQAAgEACgCQABgCAEAAIAHAAIAAAEIgGAAIgEABIAAADIAAAFIAIAAIAAAEIgIAAIAAAWg");
	this.shape_61.setTransform(74.5,178.625);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#003E74").s().p("AgBATIAAgaIADAAIAAAagAAAgMQAAAAgBgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAgDIAAgBIABAAIABAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAADQAAAAAAABQAAAAAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_62.setTransform(72.6,178.7);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#003E74").s().p("AADASQgDAAgBgCQgCgCAAgEIAAgPIgFAAIAAgEIAFAAIAAgIIAEAAIAAAIIAIAAIAAAEIgIAAIAAAPIAAADIADABIAEAAIABADIgDABg");
	this.shape_63.setTransform(70.875,178.9);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#003E74").s().p("AgLATIAAgDIAEAAIAHAAIAEAAIADgCIABgFIgBgDIgBgCIgDgBIgHgCQgEgBgCgBQgCgDAAgFQAAgFACgCQAAAAAAAAQABgBAAAAQABgBAAAAQABAAABAAIAGgBIAMABIgBADIgLAAIgEAAIgCADIgBAEIABADIAEADIAHACQAEAAACACQACADAAAEIgBAIIgEACIgIABIgLgBg");
	this.shape_64.setTransform(68.175,178.7);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#003E74").s().p("AgKAUIAGgEIADgFIABgBIgCAAIgBgBIgBgBIgMgeIAHAAIAIAXIABAEIABAAIABgEIAJgXIAGAAIgNAiQgEALgKAAg");
	this.shape_65.setTransform(189.825,185.85);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#003E74").s().p("AADAVQgDAAgCgBQgCgDAAgFIAAgSIgGAAIAAgFIAGAAIAAgKIAEAAIAAAKIALAAIAAAFIgLAAIAAASIABADIAEACIAFAAIAAAEIgDAAg");
	this.shape_66.setTransform(186.8,184.7);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#003E74").s().p("AgCAYIAAggIAEAAIAAAggAAAgPQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgDIAAgCIACgBIABAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAADQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_67.setTransform(184.7,184.45);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#003E74").s().p("AABAYQgDAAgCgCQgCgCAAgEIAAgnIAGAAIAAAmIAAADQAAAAAAAAQABAAAAABQABAAAAAAQABAAAAAAIADAAIABAEIgDABg");
	this.shape_68.setTransform(183.1,184.45);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#003E74").s().p("AgCAYIAAggIAEAAIAAAggAgBgPQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgDIAAgCIABgBIACAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAADQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_69.setTransform(181.05,184.45);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#003E74").s().p("AgHAXIgHgBIAAgtIAGAAIAAAMIgBAIQAGgGAGAAQAGAAADAEQADAEAAAIQAAAGgBADQgCAEgDACQgDACgGAAIgHgBgAgCgDIgGADIAAASIAIABQAEAAACgBIACgEIABgHIgBgHQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAIgFgBIgDABg");
	this.shape_70.setTransform(178.35,184.475);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#003E74").s().p("AgCAYIAAggIAEAAIAAAggAAAgPQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgDIAAgCIACgBIABAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAADQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_71.setTransform(175.55,184.45);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#003E74").s().p("AAKARIgJgPIgBAAIgJAPIgGAAIALgRIgKgPIAGAAIAIANIABAAIAIgNIAHAAIgLAPIALARg");
	this.shape_72.setTransform(172.925,185.15);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#003E74").s().p("AgHAPQgDgBgCgEQgCgEAAgGQAAgGACgDQACgEADgCQADgBAFAAQAHAAADACQAEADAAAFQAAAFgCABQgCADgEAAIgOAAIABAGQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAIAFABIALgBIABAEIgGACIgHAAQgFAAgDgCgAgEgLQAAAAgBABQAAAAAAABQgBAAAAABQgBAAAAABIgBAGIANAAQAEAAAAgFQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQgCgCgEAAIgFABg");
	this.shape_73.setTransform(169.375,185.175);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#003E74").s().p("AABAYQgDAAgCgCQgCgCAAgEIAAgnIAGAAIAAAmIAAADQAAAAAAAAQABAAAAABQABAAAAAAQABAAAAAAIADAAIABAEIgDABg");
	this.shape_74.setTransform(166.8,184.45);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#003E74").s().p("AgNAXIAAglQAAgEACgCQADgCAEAAIASAAIAAAFIgRAAIgDABQAAAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAALIASAAIAAAEIgSAAIAAAVg");
	this.shape_75.setTransform(163.875,184.475);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#003E74").s().p("AgMAQIAAgEIAJAAIADAAIAEAAIADgCIABgCIgBgEIgEgBIgIgCQgEgBgCgBQgCgCAAgEIABgGQABgBAAAAQABgBAAAAQABAAAAAAQABgBAAAAIAHAAIAHAAIAHABIgBAEIgDAAIgFgBIgFAAIgEABIgCABIAAADIAAACIACABIADABIAIACQAEABACABQACACAAAFQAAAEgCACQgBACgDAAIgIABIgMgBg");
	this.shape_76.setTransform(158.725,185.175);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#003E74").s().p("AgBAHIAAgNIADAAIAAANg");
	this.shape_77.setTransform(156.3,182.875);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#003E74").s().p("AgHAPQgDgBgCgEQgCgEAAgGQAAgGACgDQACgEADgCQADgBAFAAQAHAAADACQAEADAAAFQAAAFgCABQgCADgEAAIgOAAIABAGQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAIAFABIALgBIABAEIgGACIgHAAQgFAAgDgCgAgEgLQAAAAgBABQAAAAAAABQgBAAAAABQAAAAgBABIgBAGIANAAQAEAAAAgFQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQgCgCgEAAIgFABg");
	this.shape_78.setTransform(153.825,185.175);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#003E74").s().p("AgJARIAAggIAEAAIABAFQAGgGAHAAIABAAIgBAFIgBAAIgGABIgGAEIAAAXg");
	this.shape_79.setTransform(150.825,185.125);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#003E74").s().p("AgLAPQgCgCAAgFIAAgYIAGAAIAAAWQAAABAAABQAAAAAAABQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAGgDIAAgXIAGAAIAAAgIgFAAIAAgFIgHAFIgGABQgFAAgCgCg");
	this.shape_80.setTransform(147.375,185.2);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#003E74").s().p("AADAVQgDAAgCgBQgCgDAAgFIAAgSIgGAAIAAgFIAGAAIAAgKIAEAAIAAAKIALAAIAAAFIgLAAIAAASIABADIAEACIAFAAIAAAEIgDAAg");
	this.shape_81.setTransform(144.15,184.7);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#003E74").s().p("AgGAPQgDgBgCgEQgBgEgBgGQABgGABgDQACgEADgCQADgBAGAAIAFAAIAFABIgBAEIgIgBIgGABIgDAEQgBADAAAEQAAAFABACIADAEIAGABIAJAAIAAADQgEACgGAAQgGAAgDgCg");
	this.shape_82.setTransform(141.3,185.175);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#003E74").s().p("AgLAPQgCgCAAgFIAAgYIAGAAIAAAWQAAABAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAGgDIAAgXIAGAAIAAAgIgFAAIAAgFIgHAFIgGABQgFAAgCgCg");
	this.shape_83.setTransform(137.675,185.2);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#003E74").s().p("AgJARIAAggIAEAAIABAFQAGgGAHAAIABAAIgBAFIgBAAIgGABIgGAEIAAAXg");
	this.shape_84.setTransform(134.625,185.125);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#003E74").s().p("AADAVQgDAAgCgBQgCgDAAgFIAAgSIgGAAIAAgFIAGAAIAAgKIAEAAIAAAKIALAAIAAAFIgLAAIAAASIACADIADACIAFAAIABAEIgEAAg");
	this.shape_85.setTransform(131.75,184.7);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#003E74").s().p("AgNAXIAAgFIAEABIAIAAIAGgBQABAAAAAAQABAAAAAAQABgBAAAAQAAAAAAgBIABgFIAAgEIgCgCIgDgBIgJgDQgFgBgCgCQgCgDAAgGQAAgFACgDQABgDADAAIAIgBQAIAAAGABIAAAEIgOAAIgEAAIgEACIgBAFQAAAEACABQACACADABIAIACQAGABACADQABADAAAFQABAGgCACQgCADgDABIgJABQgHAAgGgBg");
	this.shape_86.setTransform(128.6,184.475);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#003E74").s().p("AgJANQgEgCgCgDQgBgDAAgFQAAgHACgDQADgEAFAAQAFAAABACQADACAAAEIAAAOIAGgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAIABgFIgBgLIAEgBIACAGIAAAHQAAAFgCADQgBADgEACQgEACgGAAQgGAAgDgCgAgKgGQgCACAAAEIABAFQABAAAAABQAAAAABABQAAAAABAAQAAAAABABIAGABIAAgNQAAgEgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABg");
	this.shape_87.setTransform(46.975,63.225);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#003E74").s().p("AAJAQQgCgBgCgDIgBABIgDABIgDgBIgBgCIgEAEIgFABQgEAAgDgCQgCgBAAgDIgBgJIAAgGIAAgLIADABIAAAFQADgCAEAAQAFAAADAEQACADAAAGIgBAHIADABIABgBIABgCIACgLQABgFACgCQADgCAEAAQADAAADACQACABABAEIABAIIgBAKQgBADgCABQgDACgDAAIgFgBgAAJgGIgBAEIgBAKIACADIAEAAIADgBQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBIABgGIgBgFIgCgDIgDgBIgCAAIgCACgAgRgEQgBACgBADQABAFABACQAAABABAAQAAABABAAQAAAAABAAQABAAABAAQADAAABgCQACgCAAgFQAAgDgCgCQgBgCgDAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAABg");
	this.shape_88.setTransform(47.6,66.825);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#003E74").s().p("AAFAOQgFAAgBgCQgCgDAAgEIAAgNIgDAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABQgCABABAEIABANIgFABIgBgPQAAgGACgDQACgCAGAAIAWAAIAAAEIgFABIAFAGQABACAAAEQAAAFgCADQgCACgFAAgAAAAEQAAABABAAQAAABAAAAQAAAAAAABQABAAAAAAIADABIACAAIAEgBIABgEIgBgFIgEgGIgHAAg");
	this.shape_89.setTransform(46.95,70.725);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#003E74").s().p("AgPAYIAAgEIAFgBIgFgGIgBgHQAAgGAGgBQgGgHAAgHQAAgEACgCQADgCAEAAIAYAAIAAAFIgWAAIgFABQAAABAAAAQgBAAAAABQAAABAAAAQAAABAAAAIABAFIAEAGIAXAAIAAAFIgWAAQgBAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAAAABQAAAAAAABIABAEIAEAHIAXAAIAAAFg");
	this.shape_90.setTransform(46.925,75.425);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#003E74").s().p("AAFAOQgFAAgBgCQgCgDAAgEIAAgNIgDAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABQgCABABAEIABANIgFABIgBgPQAAgGACgDQACgCAGAAIAWAAIAAAEIgFABIAFAGQABACAAAEQAAAFgCADQgCACgFAAgAAAAEQAAABABAAQAAABAAAAQAAAAAAABQABAAAAAAIADABIACAAIAEgBIABgEIgBgFIgEgGIgHAAg");
	this.shape_91.setTransform(46.95,80.325);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#003E74").s().p("AgWARIgBgQQAAgGACgEQADgEAFgCQAFgBAIAAQAKAAAFABQAEACADAEQACAEAAAGIgBAQgAgKgJQgEABgCADQgCACAAAEIAAAKIAlAAIAAgKQAAgEgCgCQgBgDgEgBIgMgBIgKABg");
	this.shape_92.setTransform(46.25,84.275);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#003E74").s().p("AgCAOQgEgCgCgCQgBgDAAgEQAAgGACgFIgGAAIgKAAIAAgGIAuAAIAAAFIgEAAQAFAHAAAFQAAAGgEADQgFADgIAAIgJgBgAgEgCIAAADIABAFQAAAAAAABQABAAAAAAQABABAAAAQABAAAAAAIAHABIAHgBQABAAAAAAQABAAAAgBQABAAAAAAQABgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBQAAgBAAAAIgBgEIgDgGIgSAAg");
	this.shape_93.setTransform(46.275,90.075);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#003E74").s().p("AgPAOIAAgEIAFgBQgGgIAAgGQAAgEACgCQADgCAEAAIAYAAIAAAFIgWAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAAAAAABQgBAAAAABQAAAAAAABQAAABAAAAIABAEIAEAIIAXAAIAAAFg");
	this.shape_94.setTransform(46.925,93.875);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#003E74").s().p("AAFAOQgFAAgBgCQgCgDAAgEIAAgNIgDAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABQgCABABAEIABANIgFABIgBgPQAAgGACgDQACgCAGAAIAWAAIAAAEIgFABIAFAGQABACAAAEQAAAFgCADQgCACgFAAgAAAAEQAAABABAAQAAABAAAAQAAAAAAABQABAAAAAAIADABIACAAIAEgBIABgEIgBgFIgEgGIgHAAg");
	this.shape_95.setTransform(46.95,97.775);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#003E74").s().p("AgPAOIAAgEIAFgBQgGgIAAgGQAAgEACgCQADgCAEAAIAYAAIAAAFIgWAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABQAAABAAAAIABAEIAEAIIAXAAIAAAFg");
	this.shape_96.setTransform(46.925,102.975);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#003E74").s().p("AgJADIAAgFIAgAAIAAAFgAgVADIgBAAIAAgBIAAgCQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAEAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAACQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAg");
	this.shape_97.setTransform(46.25,105.75);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#003E74").s().p("AgJANQgEgBgCgDQgBgDAAgGQAAgFABgDQACgEAEgBQADgCAGABQAGgBAEACQAEABABAEQACADAAAFQAAAGgCADQgBADgEABQgEACgGAAQgGAAgDgCgAgHgIIgEADIgBAFIABAFIAEAEIAHABIAHgBQADgCABgCIABgFIgBgFQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBgBgBAAIgHAAIgHAAg");
	this.shape_98.setTransform(46.975,108.55);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#003E74").s().p("AgKALIgBgGIgJAAIAAgFIAJAAIAAgKIAEAAIAAAKIATAAIAEgBIAAgDIAAgFIAEgBIACAEIAAAEQgBADgCACQgCACgEAAIgUAAIAAAGg");
	this.shape_99.setTransform(46.5,111.7);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#003E74").s().p("AAFAOQgFAAgBgCQgCgDAAgEIAAgNIgDAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABQgCABABAEIABANIgFABIgBgPQAAgGACgDQACgCAGAAIAWAAIAAAEIgFABIAFAGQABACAAAEQAAAFgCADQgCACgFAAgAAAAEQAAABABAAQAAABAAAAQAAAAAAABQABAAAAAAIADABIACAAIAEgBIABgEIgBgFIgEgGIgHAAg");
	this.shape_100.setTransform(46.95,114.925);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#003E74").s().p("AgPAYIAAgEIAFgBIgFgGIgBgHQAAgGAGgBQgGgHAAgHQAAgEACgCQADgCAEAAIAYAAIAAAFIgWAAIgFABQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAAAIABAFIAEAGIAXAAIAAAFIgWAAQgBAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAAAABQAAAAAAABIABAEIAEAHIAXAAIAAAFg");
	this.shape_101.setTransform(46.925,119.625);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#003E74").s().p("AgPAKIAAgEIAFgBQgGgGAAgHIAAgBIAFABIAAABIABAGIAEAGIAXAAIAAAFg");
	this.shape_102.setTransform(46.925,123.775);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#003E74").s().p("AgJAOQgEgCgCgDQgBgDAAgGQAAgFABgEQACgDAEgBQADgBAGAAQAGAAAEABQAEABABADQACAEAAAFQAAAGgCADQgBADgEACQgEABgGAAQgGAAgDgBgAgHgIIgEADIgBAFIABAGIAEACIAHABIAHgBQABAAABAAQAAAAABgBQAAAAABgBQAAAAAAAAIABgGIgBgFQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBgBgBAAIgHgBIgHABg");
	this.shape_103.setTransform(46.975,127.25);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#003E74").s().p("AgHAMIgBgGIgGAAQgEAAgDgCQgCgCAAgEIAAgJIAEAAIAAAHQAAABAAAAQAAABABABQAAAAAAABQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQABAAAAAAIAFAAIAAgKIAFAAIAAAKIAbAAIAAAFIgbAAIAAAGg");
	this.shape_104.setTransform(46.175,130.275);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#003E74").s().p("AgJANQgEgCgCgDQgBgDAAgFQAAgHACgDQADgEAFAAQAFAAABACQADACAAAEIAAAOIAGgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAIABgFIgBgLIAEgBIACAGIAAAHQAAAFgCADQgBADgEACQgEACgGAAQgGAAgDgCgAgKgGQgCACAAAEIABAFQABAAAAABQAAAAABAAQAAABABAAQAAAAABABIAGABIAAgNQAAgEgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABg");
	this.shape_105.setTransform(46.975,133.525);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#003E74").s().p("AgWARIgBgQQAAgGACgEQADgEAFgCQAFgBAIAAQAKAAAFABQAEACADAEQACAEAAAGIgBAQgAgKgJQgEABgCADQgCACAAAEIAAAKIAlAAIAAgKQAAgEgCgCQgBgDgEgBIgMgBIgKABg");
	this.shape_106.setTransform(46.25,137.475);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#003E74").s().p("AgKAUIAGgEIADgFIABgBIgCAAIgBgBIgBgBIgMgeIAHAAIAIAXIABAEIABAAIABgEIAJgXIAGAAIgNAiQgEALgKAAg");
	this.shape_107.setTransform(420.175,185.85);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#003E74").s().p("AADAVQgDAAgCgBQgCgDAAgFIAAgSIgGAAIAAgFIAGAAIAAgKIAFAAIAAAKIAKAAIAAAFIgKAAIAAASIABADIADACIAFAAIABAEIgEAAg");
	this.shape_108.setTransform(417.15,184.7);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#003E74").s().p("AgCAYIAAggIAEAAIAAAggAgBgPQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgDIAAgCIABgBIACAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAADQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_109.setTransform(415.05,184.45);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#003E74").s().p("AABAYQgDAAgCgCQgCgCAAgEIAAgnIAFAAIAAAmIABADQAAAAAAAAQABAAAAABQABAAAAAAQAAAAABAAIADAAIABAEIgDABg");
	this.shape_110.setTransform(413.45,184.45);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#003E74").s().p("AgCAYIAAggIAFAAIAAAggAgBgPQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgDIAAgCIABgBIACAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAADQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_111.setTransform(411.4,184.45);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#003E74").s().p("AgGAXIgIgBIAAgtIAGAAIAAAMIAAAIQAFgGAGAAQAGAAADAEQADAEAAAIQAAAGgCADQgBAEgDACQgDACgFAAIgHgBgAgDgDIgFADIAAASIAIABQADAAACgBIADgEIABgHIgBgHQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAIgFgBIgEABg");
	this.shape_112.setTransform(408.7,184.475);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#003E74").s().p("AgCAYIAAggIAFAAIAAAggAgBgPQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgDIAAgCIABgBIACAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAADQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_113.setTransform(405.9,184.45);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#003E74").s().p("AAKARIgJgPIgBAAIgJAPIgGAAIALgRIgKgPIAGAAIAIANIABAAIAIgNIAHAAIgLAPIALARg");
	this.shape_114.setTransform(403.275,185.15);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#003E74").s().p("AgHAPQgDgBgCgEQgCgEAAgGQAAgGACgDQACgEADgCQADgBAFAAQAHAAADACQAEADAAAFQAAAFgCABQgCADgEAAIgOAAIABAGQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAIAFABIALgBIABAEIgGACIgHAAQgFAAgDgCgAgEgLQAAAAgBABQAAAAAAABQgBAAAAABQAAAAgBABIgBAGIANAAQAEAAAAgFQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQgCgCgEAAIgFABg");
	this.shape_115.setTransform(399.725,185.175);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#003E74").s().p("AABAYQgDAAgCgCQgCgCAAgEIAAgnIAFAAIAAAmIABADQAAAAAAAAQABAAAAABQABAAAAAAQAAAAABAAIADAAIABAEIgDABg");
	this.shape_116.setTransform(397.15,184.45);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#003E74").s().p("AgNAXIAAglQAAgEACgCQADgCAEAAIASAAIAAAFIgRAAIgDABQAAAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAALIASAAIAAAEIgSAAIAAAVg");
	this.shape_117.setTransform(394.225,184.475);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#003E74").s().p("AgMAQIAAgEIAJAAIADAAIAEAAIADgCIABgCIgBgEIgEgBIgIgCQgEgBgCgBQgCgCAAgEIABgGQABgBAAAAQAAgBABAAQAAAAABAAQABgBAAAAIAHAAIAHAAIAHABIgBAEIgDAAIgFgBIgFAAIgEABIgCABIAAADIAAACIACABIADABIAIACQAEABACABQACACAAAFQAAAEgCACQgBACgDAAIgIABIgMgBg");
	this.shape_118.setTransform(389.075,185.175);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#003E74").s().p("AgBAHIgBgNIAFAAIgBANg");
	this.shape_119.setTransform(386.65,182.875);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#003E74").s().p("AgHAPQgDgBgCgEQgCgEAAgGQAAgGACgDQACgEADgCQADgBAFAAQAHAAADACQAEADAAAFQAAAFgCABQgCADgEAAIgOAAIABAGQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAIAFABIALgBIABAEIgGACIgHAAQgFAAgDgCgAgEgLQAAAAgBABQAAAAgBABQAAAAAAABQgBAAAAABIgBAGIANAAQAEAAAAgFQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQgCgCgEAAIgFABg");
	this.shape_120.setTransform(384.175,185.175);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f("#003E74").s().p("AgJARIAAggIAEAAIABAFQAGgGAHAAIABAAIgBAFIgBAAIgGABIgGAEIAAAXg");
	this.shape_121.setTransform(381.175,185.125);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#003E74").s().p("AgLAPQgCgCAAgFIAAgYIAGAAIAAAWQAAABAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAGgDIAAgXIAGAAIAAAgIgFAAIAAgFIgHAFIgGABQgFAAgCgCg");
	this.shape_122.setTransform(377.725,185.2);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.f("#003E74").s().p("AADAVQgDAAgCgBQgCgDAAgFIAAgSIgGAAIAAgFIAGAAIAAgKIAFAAIAAAKIAKAAIAAAFIgKAAIAAASIABADIADACIAFAAIABAEIgEAAg");
	this.shape_123.setTransform(374.5,184.7);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.f("#003E74").s().p("AgGAPQgDgBgCgEQgCgEAAgGQAAgGACgDQACgEADgCQAEgBAEAAIAGAAIAFABIgBAEIgJgBIgFABIgDAEQgBADgBAEQABAFABACIADAEIAFABIAKAAIAAADQgEACgHAAQgEAAgEgCg");
	this.shape_124.setTransform(371.65,185.175);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.f("#003E74").s().p("AgLAPQgCgCAAgFIAAgYIAGAAIAAAWQAAABAAABQAAAAAAABQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAGgDIAAgXIAGAAIAAAgIgFAAIAAgFIgHAFIgGABQgFAAgCgCg");
	this.shape_125.setTransform(368.025,185.2);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.f("#003E74").s().p("AgJARIAAggIAEAAIABAFQAGgGAHAAIABAAIgBAFIgBAAIgGABIgGAEIAAAXg");
	this.shape_126.setTransform(364.975,185.125);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.f("#003E74").s().p("AADAVQgDAAgCgBQgCgDAAgFIAAgSIgGAAIAAgFIAGAAIAAgKIAFAAIAAAKIAKAAIAAAFIgKAAIAAASIAAADIAEACIAFAAIAAAEIgDAAg");
	this.shape_127.setTransform(362.1,184.7);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.f("#003E74").s().p("AgOAXIABgFIAFABIAHAAIAGgBQABAAAAAAQABAAAAAAQABgBAAAAQAAAAABgBIABgFIgBgEIgCgCIgEgBIgIgDQgFgBgCgCQgCgDgBgGQAAgFACgDQACgDADAAIAIgBQAIAAAFABIAAAEIgNAAIgFAAIgCACIgBAFQgBAEACABQACACACABIAJACQAFABACADQACADABAFQAAAGgCACQgBADgEABIgJABQgGAAgIgBg");
	this.shape_128.setTransform(358.95,184.475);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.f("#003E74").s().p("AgJANQgEgCgCgDQgBgDAAgFQAAgHACgDQADgEAFAAQAFAAABACQADACAAAEIAAAOIAGgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAIABgFIgBgLIAEgBIACAGIAAAHQAAAFgCADQgBADgEACQgEACgGAAQgGAAgDgCgAgKgGQgCACAAAEIABAFQAAAAABABQAAAAABABQAAAAABAAQAAABABAAIAGABIAAgNQAAgEgFAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABg");
	this.shape_129.setTransform(281.625,81.475);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.f("#003E74").s().p("AgJAMQgEgCgCgDQgBgDAAgFIAAgGIABgFIAEABIgBAIIABAGIAEADQADACAEAAQAFAAACgCIAEgDIABgGIAAgJIADgBQACAGAAAGQAAAFgCADQgBADgEACQgEABgGAAQgGAAgDgBg");
	this.shape_130.setTransform(281.625,84.9);

	this.shape_131 = new cjs.Shape();
	this.shape_131.graphics.f("#003E74").s().p("AgPAKIAAgEIAFgBQgGgGAAgHIAAgBIAFABIAAABIABAGIAEAGIAXAAIAAAFg");
	this.shape_131.setTransform(281.575,87.725);

	this.shape_132 = new cjs.Shape();
	this.shape_132.graphics.f("#003E74").s().p("AgJANQgEgBgCgDQgBgDAAgGQAAgFABgDQACgDAEgCQADgBAGgBQAGABAEABQAEACABADQACADAAAFQAAAGgCADQgBADgEABQgEACgGABQgGgBgDgCgAgHgIIgEADIgBAFIABAFIAEAEIAHABIAHgBQADgBABgDIABgFIgBgFQgBgCgDgBIgHAAIgHAAg");
	this.shape_132.setTransform(281.625,91.2);

	this.shape_133 = new cjs.Shape();
	this.shape_133.graphics.f("#003E74").s().p("AgOAOQgEAAgCgCQgCgDAAgEIAAgSIAFAAIAAARIABADQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIALAAIAAgSIAEAAIAAASIAVAAIAAAGg");
	this.shape_133.setTransform(280.925,94.775);

	this.shape_134 = new cjs.Shape();
	this.shape_134.graphics.f("#003E74").s().p("AgJAMQgEgCgCgDQgBgEAAgEIAAgGIABgFIAEABIgBAJIABAFIAEADQADABAEABQAFgBACgBIAEgDIABgFIAAgKIADgBQACAFAAAHQAAAEgCAEQgBADgEACQgEABgGAAQgGAAgDgBg");
	this.shape_134.setTransform(281.625,99.85);

	this.shape_135 = new cjs.Shape();
	this.shape_135.graphics.f("#003E74").s().p("AgIADIAAgFIAfAAIAAAFgAgVADIgBAAIgBgBIAAgCQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAEAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIAAACQAAAAAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_135.setTransform(280.9,102.35);

	this.shape_136 = new cjs.Shape();
	this.shape_136.graphics.f("#003E74").s().p("AgPAYIAAgEIAFgBIgFgGIgBgHQAAgGAGgBQgGgHAAgHQAAgEACgCQADgCAEAAIAYAAIAAAFIgWAAIgFABQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAAAIABAFIAEAGIAXAAIAAAFIgWAAQgBAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAAAABQAAAAAAABIABAEIAEAHIAXAAIAAAFg");
	this.shape_136.setTransform(281.575,106.125);

	this.shape_137 = new cjs.Shape();
	this.shape_137.graphics.f("#003E74").s().p("AgNANQgBgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAIAAgHIAAgHIABgHIAEABIAAADIgBAFIAAAFIABAEIABACIADAAIACAAIABgCIABgDIACgIQABgEABgCQACgCAFAAQAEAAACACQACABAAADIABAHIgBANIgEAAIAAgJIAAgDIAAgEIgCgDIgCgBIgEABIgBAEIgCAIQgBAEgBACQgCACgEAAIgGgBg");
	this.shape_137.setTransform(281.625,110.825);

	this.shape_138 = new cjs.Shape();
	this.shape_138.graphics.f("#003E74").s().p("AgIADIAAgEIAfAAIAAAEgAgVADIgBAAIgBgCIAAgBQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAEAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAABQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_138.setTransform(280.9,113.35);

	this.shape_139 = new cjs.Shape();
	this.shape_139.graphics.f("#003E74").s().p("AgJANQgEgCgCgDQgBgDAAgFQAAgHACgDQADgEAFAAQAFAAABACQADACAAAEIAAAOIAGgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAIABgFIgBgLIAEgBIACAGIAAAHQAAAFgCADQgBADgEACQgEACgGAAQgGAAgDgCgAgKgGQgCACAAAEIABAFQAAAAABABQAAAAABAAQAAABABAAQAAAAABABIAGABIAAgNQAAgEgFAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABg");
	this.shape_139.setTransform(281.625,115.975);

	this.shape_140 = new cjs.Shape();
	this.shape_140.graphics.f("#003E74").s().p("AgTANQgDgBAAgDIgBgJQAAgHABgGIAEAAIAAANIAAAFIACADIAFACQAEAAABgCQACgBABgDIACgJQABgFADgDQADgBAFAAQAGgBACACQADACABADIABAIQAAAIgBAGIgFAAIABgEIAAgIIgBgGQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgFgCIgEABIgCACIgBADIgDAJQgBAFgCACQgDADgGgBQgFAAgDgCg");
	this.shape_140.setTransform(280.925,119.7);

	this.shape_141 = new cjs.Shape();
	this.shape_141.graphics.f().s("#003E74").ss(2,1,1).p("EAhZALZIABAAQABAAABAAIAEAAIAFAAEAhwALZIABABIgnAdEAhKAK8IAlAcACbrOIAfgoIAdAnAizLZIABAAQABAAABAAIAEAAIAFAAAicLZIACABIgoAdAjCK8IAlAcADGLZIgMAAIAA3PEghSgL2IAdAnEghwgLOIAegoEghFALZIgNAAIAA3PAi3LZI97AAEAhVALZI97AA");
	this.shape_141.setTransform(275.225,99.8);

	this.shape_142 = new cjs.Shape();
	this.shape_142.graphics.f().s("#000000").ss(2,0,0,4).p("EAhDAABIgEAAEAhPAAAIAGAAQACAAACAAIABABEAhGAABQABgBABAAQABAAABAAAjGABQABgBABAAQABAAABAAAjJABIgEAAAi9AAIAGAAQACAAACAAIABABACwABIAHAAQADAAADAAQADAAAEAAEghbAABIAGAAQADAAAEAAQADAAADAA");
	this.shape_142.setTransform(277.4024,172.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_142},{t:this.shape_141},{t:this.shape_140},{t:this.shape_139},{t:this.shape_138},{t:this.shape_137},{t:this.shape_136},{t:this.shape_135},{t:this.shape_134},{t:this.shape_133},{t:this.shape_132},{t:this.shape_131},{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(288.8,222.9,241.49999999999994,164.6);
// library properties:
lib.properties = {
	id: '4B93EBDA609CD5499832C33DCA53321E',
	width: 550,
	height: 400,
	fps: 60,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['4B93EBDA609CD5499832C33DCA53321E'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;